//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokEkstresi
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokEkstresi
    {
        public int SiraNo { get; set; }
        public string IslemTur { get; set; }
        public string EvrakNo { get; set; }
        public string Tarih { get; set; }
        public Nullable<decimal> GirisMiktar { get; set; }
        public Nullable<decimal> CikisMiktar { get; set; }
        public Nullable<decimal> StokMiktar { get; set; }
    }
}
