//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokEkstresi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestDBEntities : DbContext
    {
        public TestDBEntities()
            : base("name=TestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STI> STI { get; set; }
        public virtual DbSet<STK> STK { get; set; }
        public virtual DbSet<StokEkstresi> StokEkstresi { get; set; }
    
        public virtual ObjectResult<sp_Stok_Ekstresi_Result> sp_Stok_Ekstresi(string malKodu, Nullable<int> baslangicTarihi, Nullable<int> bitisTarihi)
        {
            var malKoduParameter = malKodu != null ?
                new ObjectParameter("malKodu", malKodu) :
                new ObjectParameter("malKodu", typeof(string));
    
            var baslangicTarihiParameter = baslangicTarihi.HasValue ?
                new ObjectParameter("baslangicTarihi", baslangicTarihi) :
                new ObjectParameter("baslangicTarihi", typeof(int));
    
            var bitisTarihiParameter = bitisTarihi.HasValue ?
                new ObjectParameter("bitisTarihi", bitisTarihi) :
                new ObjectParameter("bitisTarihi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Stok_Ekstresi_Result>("sp_Stok_Ekstresi", malKoduParameter, baslangicTarihiParameter, bitisTarihiParameter);
        }
    }
}
